version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/timelytics
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    environment:
      - MONGO_URL=mongodb://mongo:27017/timelytics
      - REDIS_URL=redis://redis:6379
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
